server:
  port: 7076
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms_backend
    username: root
    password:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 4

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      apache:
        http: DEBUG
    root: INFO
    com.livspace.service_framework: INFO

axle:
  client:
    id: StarMSFe-G4DsKI
    secret: 2SXhLxG7prabkWl2rHQptbpIyt8XH9yg
