server:
  port: 7076
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms_backend
    username: root
    password:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 4

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379